Updated: eZpedia source kernel and extension code updated to eZ Publish 2013.04 Legacy Stack sources

diff --git a/ezp/extension/ezfind/bin/scripts/debian/solr b/ezp/extension/ezfind/bin/scripts/debian/solr
--- a/ezp/extension/ezfind/bin/scripts/debian/solr
+++ b/ezp/extension/ezfind/bin/scripts/debian/solr
@@ -1,73 +1,121 @@
 #! /bin/sh
 #
 # eZ Find init script for debian.
-# 
-# Usage:
-# 
-# Set the correct SOLR_HOME value, and copy this file to /etc/init.d
-# Symlink to /etc/init.d/solr to /etc/rc3.d/S70solr and /etc/rc5.d/S70solr
 #
-# Example:
-# cp solr /etc/init.d/solr
-# cd /etc/init.d && chmod 755 solr
-# cd /etc/rc3.d && ln -s ../init.d/solr S70solr
-# cd /etc/rc5.d && ln -s ../init.d/solr S70solr
-# cd /etc/rc3.d && ln -s ../init.d/solr K70solr
-# cd /etc/rc5.d && ln -s ../init.d/solr K70solr
+# Usage:
+#
+# Set the correct SOLR_HOME value, and copy (or symlink) this file to
+# /etc/init.d, then run "update-rc.d solr defaults" as root
 
-set -e
+### BEGIN INIT INFO
+# Provides:          solr
+# Required-Start:    $local_fs $remote_fs
+# Required-Stop:     $local_fs $remote_fs
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Start/stop solr
+# Description:       Start/stop solr
+### END INIT INFO
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+# Replace with the java directory of your eZ Find extension
+# (example: /var/www/ezpublish/extension/ezfind/java)
+SOLR_HOME=/usr/local/solr/java
+
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Solr indexing server"
 NAME=solr
-SOLR_HOME= #INSERT Solr path here, example: /var/www/ezpublish/extension/ezfind/java
-DAEMON=$SOLR_HOME/$NAME.sh
+DAEMON=/usr/bin/java
+DAEMON_ARGS="-jar start.jar"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
-# Gracefully exit if the package has been removed.
-test -x $DAEMON || exit 0
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
 
 #
-#	Function that starts the daemon/service.
+# Function that starts the daemon/service
 #
-d_start() {
-	start-stop-daemon --start --pidfile $PIDFILE \
-                --chdir $SOLR_HOME --background --make-pidfile \
-		--exec $DAEMON
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test -- $DAEMON_ARGS > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --chdir $SOLR_HOME --background --make-pidfile --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+    sleep 2
 }
 
 #
-#	Function that stops the daemon/service.
+# Function that stops the daemon/service
 #
-d_stop() {
-	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-		--name java
-        rm -f $PIDFILE 
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	rm -f $PIDFILE
+	return "$RETVAL"
 }
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: $NAME"
-	d_start
-	echo "."
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   stop)
-	echo -n "Stopping $DESC: $NAME"
-	d_stop
-	echo "."
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
+  status)
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
   restart|force-reload)
-	echo -n "Restarting $DESC: $NAME"
-	d_stop
-	sleep 1
-	d_start
-	echo "."
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
-	exit 1
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
 	;;
 esac
 
-exit 0
+:
